### ISSUE TITLE
ANUNCIANTES

### ISSUE THREAD

**Issue by ascrs** [tonetlds/juscchneider.com#5]
Na HOME do site...
ao lado do post principal onde temos 2 anunciantes, ela fechou com o BELLA CITTA, e eles querm o espaço inteiro, sendo assim transformamos em 1 só e preciso das medidas para passar para o pessoal do BELLA confeccionar o banner/gif/anuncio - não sei como devemos chamar.

Mais abaixo entre o INSTA e o PINTEREST temos um anuncio inteiro digamos.
Ela quer dividir ele em 3 anunciantes, pois parece q já tem 1 fechado tbm.

Entendidos?

**Comment by tonetlds** [comment]
**Quanto à nova estrutura...**
OK, Feito como solicitado:

![image](https://cloud.githubusercontent.com/assets/2693019/15164501/9f478870-16e5-11e6-9710-49c1900da65a.png)


**Quando ao tamanho exato para confecção das artes...**
Como o site é responsivo, cada tamanho de tela exibirá os blocos de anúncios em tamanhos diferentes. Difícil explicar, mas ainda preciso estudar como tratar isso.
Pra entender, vejam nos prints...

Tela grande - **336x455**
![image](https://cloud.githubusercontent.com/assets/2693019/15164579/2e354bbc-16e6-11e6-8f51-78c45861e8af.png)

Tela média - **750x300**
![image](https://cloud.githubusercontent.com/assets/2693019/15164622/74b68326-16e6-11e6-8380-7d169b82814f.png)

Tela pequena - **336x280**
![image](https://cloud.githubusercontent.com/assets/2693019/15164647/9ee16008-16e6-11e6-9876-9c4ceb67b911.png)

**Comment by ascrs** [comment]
Então... o que teremos que passar pra eles é alguns formatos "chave" onde conforme for a tela, ele busca por tal formato... não!?

Não sei se me diz entender...

Tipo eles vão passar o mesmo anúncio em 2 ou 3 formatos e conforme for a navegação ele adapta.

Um pra desktop tal resolução...
um pra tablet... tal resolução...
um pra celular... tal resolução...

Não seria assim q funciona na maioria das vezes!?

**Comment by tonetlds** [comment]
Consegui chegar num padrão que acredito ficar bom em todas as resoluções. Segue:
![image](https://cloud.githubusercontent.com/assets/2693019/15227721/fad4bac6-185e-11e6-9efa-8f69b36ba9c9.png)
