### ISSUE TITLE
HOME - NOVA SESSÃO

### ISSUE THREAD

**Issue by ascrs** [tonetlds/juscchneider.com#6]
Ainda na HOME.

Precisamos criar uma nova sessão que ficará abaixo dos POSTS...
Descrevendo ela... seria assim atualmente, nesta ordem:
LOGO / MENUS / POSTS / INSTA / ANUNCIOS / PINTEREST / REDES SOCIAIS

Agora teríamos:
LOGO / MENUS / POSTS / COLUNAS / ANUNCIOS / INSTA / PINTEREST / ANUNCIOS GOOGLE ADWORDS / REDES SOCIAIS

DEFINIÇÃO DA NOVA SESSÃO
Serão colunas que pessoas vão escrever para o BLOG dela.
Ela disse ter duas atualmente: Uma foi fechada com o BELLA CITTA, que será semanal, e a Outra é de um amigo... http://margotmagazine.com.br/ ... neste site tu entenderá o que falo...
abaixo do NEWS: últimos posts... temos ali várias postagens com títulos escritos em cima, uma imagem e um pedaço da matéria..
Vamos dividir em duas colunas e fazer bem como este site...
Um título (que será o nome da coluna), uma imagem e um pedaço das postagem com um botão de LEIA MAIS ou só MAIS o que tu achar interessante...

BELLA NEWS e BEAUTÉ - são os nomes das colunas...
Usa a fonte q tu tinha escrito INSTAGRAM e PINTEREST antes.... bem simples...

Acho que é isto.. acredito estar bem explicado.

**Comment by tonetlds** [comment]
Interessante, porém...
Isto é novo, requer novo orçamento, pois não constava na negociação.
